export { ApiClient, createApiClient, codeFromStatus, swrFetcher } from './client'
export type { ApiClientConfig, RequestOptions } from './client'
export {
  ApiClientError,
  SessionExpiredError,
  ValidationError,
  NetworkUnreachableError,
  codeFromStatus as codeFromStatusLegacy,
} from './errors'
export type {
  Role,
  User,
  SessionResponse,
  LoginResponse,
  RegisterResponse,
  Writing,
  WritingStatus,
  WritingsListResponse,
  Chapter,
  Wallet,
  WalletResponse,
  Subscription,
  SubscriptionTier,
  SubscriptionResponse,
  LibraryItem,
  LibraryResponse,
  ApiErrorBody,
  Json,
} from './types'
export {
  RoleSchema,
  UserSchema,
  SessionResponseSchema,
  LoginResponseSchema,
  RegisterResponseSchema,
  WritingSchema,
  WritingStatusSchema,
  WritingsListResponseSchema,
  ChapterSchema,
  WalletSchema,
  WalletResponseSchema,
  SubscriptionSchema,
  SubscriptionTierSchema,
  SubscriptionResponseSchema,
  LibraryItemSchema,
  LibraryResponseSchema,
  ApiErrorBodySchema,
} from './types'